---
title: "**Synapse Weekly Digest**"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
#install.packages('rmarkdown')
#install.packages('knitr')
require(knitr)
# install.packages("tinytex") # Run first time you use the script - No need after. 
# tinytex::install_tinytex() # Run first time you use the script - No need after. 

opts_chunk$set(echo = TRUE)
options(digits = 3)
#opts_knit$set(root.dir ="~/StateGec")
```

```{r message = FALSE, echo = FALSE}
# Import in subset claims data 
synapse_data <- read.csv("Synapse Disinformation Database.csv")

```

```{r message = FALSE, echo = FALSE}
# Change Date Format
synapse_data$Date <- format(as.Date(synapse_data$Date,
  format = "%m/%d/%Y"), "%d %b %Y")

```


```{r echo=FALSE, include=TRUE, results = "asis"}
template <- "## %.0f. Submitted by Post in %s on %s\n
%s campaign identified on %s\n
Description: %s\n
Source URL: %s\n
Additional Notes: %s

" 

for (i in seq(nrow(synapse_data))) {
  current <- synapse_data[i, ]
  cat(sprintf(template, current$Entry.ID, current$Regional.Post, current$Date, current$Media, current$Platform, current$Description, current$Source...URL, current$Notes))
}
```