#### Using R Markdown ####
# RMarkdown can be used to literally print your code in PDF (basic) or generate reports of your work (advanced)

# A .Rmd file has three types of content
  # Metadata (Guides Rmarkdown build process)
  # Text
  # Code Chunks 

# We can open an Rmarkdown file in the Rstudio IDE for productive notebook interface
  # You can even interact it with Python, Sequal, or other languages 

## The Render function can be used to build a report from a file  -> this performs the same function as using Knit
    # R markdown will export the file into a familiar format like PDF, HTML, Word, Apps, Websites, etc. and runs the code and embeds the output into the document. 

# Initialize 
install.packages('rmarkdown')
library(rmarkdown)

## Knit
    # Cue to 1-example.Rmd file 
    # When knitting/rendering, the file generated is processed by pandoc which is responsible for creating the finished format. Pandoc can convert documents. As simple as that. But with render, we only have to use one function. 

#### Example File: 1-example.Rmd ####
## Code Chunks - How to add them in
    # Three ways to add them in
    # 1. The easiest thing to do is to write in your code, highlight it, and     then press Ctrl + Alt + I (Cmd + Option + I for Mac users)
    # 2. You can also use the Add Chunk command in the editor tool bar. 
      # This will give you the chunk zone and then you can write whatever         you want within that zone. 
    # 3. Just manually enter it in with ```{r} and ```

#### Example File: 2-chunks.Rmd ####
  # You include the options within that original bracket part. 
      # include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks. You can use this when you are running a function mainly for eventual use in your output but are not concerned with seeing the output of that function. Generating a variable for example. 
      # echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
      # message = FALSE prevents messages that are generated by code from appearing in the finished file.
      # warning = FALSE prevents warnings that are generated by code from appearing in the finished.
      # fig.cap = "..." adds a caption to graphical results.

#### Example File - 3-inline.Rmd
# The {r} part is also what allows RMarkdown to insert code                   directly into the rext of the .RMD file.
# You can easily go in and update the report to refer to something else. 


#### Example File - 5-parameters ####
## Parameters ##
    ## R markdown can include multiple data sets via parameter specification
        ## To do this, we use the params field in our metadata section. 
        ## To access this as part of the codes you run then, you would specify via params$[param name]
              ## If you don't want to do it manually, you could always use the "Knit with Parameters" option in the dropdown menu.
                    ## Can set parameters, render, and preview the report all within one step
      ## This is useful when you want to do the same functions for different inputs (regions, departments, time periods, etc.)


#### Example File - 6-tables ####
    # You can use the Knitr::Kable function in R if you don't like the default output R uses in the console.
    # The example uses results='asis' to ensure that the raw table output isn't processed further by knitr. 

#### Example File - Markdown Basics ####
## Pandoc is what we used to write things into our outputted reports. 
  ## You can use it to make headers, lists, links, images, block quotes, latex equations, horizontal rulers, etc. 

#### Example File - 8-outputs ####
#### Output Files ####
# You can set the output_format argument of render to render your .Rmd file into any of R Markdown's supported formats 
# Can just write it directly into the console or into a separate R script (i.e. not in the .Rmd itself)
# render("1-example.Rmd", output_format = "word_document")
      # If you don't specify the output_format, r defaults to html

# If you don't want to code render, you can also just use the Knit to menu feature 

# For a list of possible outputs: http://rmarkdown.rstudio.com/lesson-9.html

# Output specifications go in the metadata section:
 # Reference ?html_document for more information on how to structure the outputs. 

#### Cheat Sheets ####
# If you ever have any challenges or forget something, you can just use the R Markdown Cheat Sheet. 
# Help -> Cheatsheet
# Help -> Markdown Quick Reference 









